spring:
  application:
    name: test
  datasource:
    url: jdbc:postgresql://localhost:5432/technical_test
    username: postgres
    password: herrera21
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  api-docs:
    enable: true

logging:
  level:
    com.cetad.test: DEBUG

server:
  port: 8090